### PR TITLE
Use a DataList element to display cities

### PR DESCRIPTION
**Pull request by jorgeramirez**
I implemented what #47 suggests. The implementation is quite simple, but it does the job :)

### CODE REVIEW

**Comment by jorgeramirez** [comment]
In the following, you can see how it looks.

out

**Comment by jorgeramirez** [comment]
I'll add a bit more love to the responsiveness of this new feature later tonight. I realized the responsiveness could be improved. I'll update the PR when it's done.

**Comment by jorgeramirez** [comment]
Updated the PR. It looks like this on mobile now:

out

**Comment by migueljoba** [comment]
Buenisimo!

**Pull request merged**
